### ISSUE TITLE
The comment reply box has no border

### ISSUE THREAD

**Issue by rprince** [jscott1989/happening#31]
It's not clear where to write the comment. Put border: 1px solid black; in the css.

**Comment by jscott1989** [comment]
This isn't as easy to fix as it first looks. It seems to be a problem with the library we're using.

Considering moving away from markdown and into something more WYSIWYG (since it's now aimed more broadly than just programmers) so we'll see if this is needed.

**Comment by jscott1989** [comment]
fixed
